# Generated by Django 5.2.7 on 2025-12-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_img_blog_image_alter_blog_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='img',
        ),
    ]
