# Generated by Django 5.2.7 on 2025-12-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_image_blog_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('content', models.TextField()),
                ('img', models.ImageField(upload_to='about/')),
                ('background', models.TextField()),
                ('teamwork', models.TextField()),
                ('our_core_value', models.TextField()),
            ],
        ),
    ]
